### PR TITLE
Feature: Added Kubernetes API server discovery

### PR DESCRIPTION
**Pull request by 0xquark**

### CODE REVIEW

**Comment by 0xquark** [comment]
Hi, @slashben! When I test the Kubeapiserver on my local machine, I can find it successfully. However, when I attempt to test it using the app.yaml file on the pod, it seems that the port is not accessible. Could you please review the app.yaml file and identify if there's some error

The output should be :

image

However I get this while running the tests:

image

I think the problem is with the port 6443 being not exposed, it's not detecting it as an open port.

**Comment by 0xquark** [comment]
I ran this:
```
+ kubectl exec -it bash-pod -n test-fe3959ca -- wget -qO- kubeapiserver-service:6443
wget: can't connect to remote host (10.97.245.146): Connection refused
```
So the 6443 port is not accessible within the pod

**Comment by slashben** [comment]
> I ran this:
> 
> ```
> + kubectl exec -it bash-pod -n test-fe3959ca -- wget -qO- kubeapiserver-service:6443
> wget: can't connect to remote host (10.97.245.146): Connection refused
> ```
> 
> So the 6443 port is not accessible within the pod

Looks like the Pod is in crash-loop since the API server cannot start (to run API server you need ETCD

```
W0628 19:27:33.108251       1 services.go:37] No CIDR for service cluster IPs specified. Default value which was 10.0.0.0/24 is │
│ I0628 19:27:33.205111       1 serving.go:342] Generated self-signed cert (/var/run/kubernetes/apiserver.crt, /var/run/kubernete │
│ I0628 19:27:33.205122       1 server.go:565] external host was not specified, using 10.244.0.3                                  │
│ W0628 19:27:33.205127       1 authentication.go:523] AnonymousAuth is not allowed with the AlwaysAllow authorizer. Resetting An │
│ E0628 19:27:33.205232       1 run.go:74] "command failed" err="[--etcd-servers must be specified, service-account-issuer is a r │
```

**Comment by slashben** [comment]
I have solved it!

It is simply too much fuss to start an API server just for the sake of the test. Setting up an API server requires ETCD, certificates, keys, and stuff that is simple not worth our time here.

What I did is the ability for the test configuration to use an existing service which is available in the cluster: the API server :)

Check it out!

**Comment by 0xquark** [comment]
Thanks! @slashben. That's quite a good approach to use the existing resources.

**Comment by slashben** [comment]
@0xquark , Kubelet is going to be tricky. In its case, we might want to put the test Pod on the host network to be able to reuse the connection

**Pull request merged**
