### PR TITLE
Added CLI for Kubenetworkscan Scan Command 

### LINKED ISSUE #3: Implement a test CLI for the package

### PR DESCRIPTION
**Pull request by 0xquark**
Fixes #3 

`kubenetworkscan --tcp/udp <host or range or list>  <ports> <services>`

Currently only PortDiscovery Works, Service discovery is in WIP!

### CODE REVIEW

**Comment by 0xquark** [comment]
Do we need real time port discovery? @slashben 
Printing out when the port is discovered or we just print the result at the end.
image

**Comment by slashben** [comment]
In general we need the following information:
- Ports open?
- Over these ports, what services are behind them?
- Are these services authenticated?

So in the above case, I'd return the results of the service discovery

B

**Comment by 0xquark** [comment]
Yess @slashben ! this will ofc be provided. I am asking about the real time result which you can see in the above screenshot '8.8.8.8/tcp open' . Basically also printing out the ports open and services open in runtime.
Once all the ports and services are discovered, we can print the whole result.

**Comment by slashben** [comment]
Oh, got it. I am not sure that live results are important, if it is easy
for us, let's do it. But for feeding the data to Kubescape, it is not
important

**Comment by 0xquark** [comment]
@slashben Servicediscovery works now! I need help with application layer discovery in it though for detecting it.
image

**Comment by 0xquark** [comment]
> @0xquark want to meet tomorrow?

Sure! The usual time?

**Review by slashben — APPROVED** [review]

**Comment by slashben** [comment]
Looks great!

**Pull request merged**
